#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Complete Entity Resolution Engine

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
npm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js frontend..."
npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Background Processes:"
echo "  Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop all services:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Next Steps:"
echo "  1. Navigate to http://localhost:3000"
echo "  2. Upload test documents"
echo "  3. Run entity resolution engine"
echo "  4. View entity graph visualization"
echo ""
